#Two-sample MR analyses of UKB pQTLs on psychiatric outcomes
#This script:
#Imports all GWAS inflammation datasets from UKB PPP
#Extracts genome-wide significant and independent pQTLs
#Extracts from outcome, harmonises & performs two-sample MR
#Saves harmonised datasets as well as IVW & Wald ratio output for supplementary material

setwd("/path/UKBGWAS_local_directory")

#Load all immunological protein GWAS from UKB

files<- list.files(path="/path/UKBGWAS_local_directory/", 
pattern="*.txt$", full.names=TRUE, recursive=FALSE)

#Load necessary packages

library(mrpipeline)
library(dplyr)
library(biomaRt)
library(TwoSampleMR)
library(tidyr)

gwasvcf::set_bcftools("/hpcpath/bcftools")

mart.gene <- biomaRt::useMart(biomart = "ensembl",
                                  host="https://www.ensembl.org",
                                  dataset = "hsapiens_gene_ensembl")

#List all psychiatric GWAS data
				  
outcome_files <- list.files(path="/path/psychiatric_data", 
pattern="*.txt$", full.names=TRUE, recursive=FALSE) 

#Loop to conduct mr analyses across all biomarkers and psychiatric outcomes

lapply(list(files), function(x){
  for(x in files) {
  
  tryCatch({
file<- vroom::vroom(x)
file_df<- as.data.frame(file)

#Extraction of genome-wide significant pQTLs

file_i<- file_df[which(file_df$P<=5e-08),]

#Formating necessary for clumping and subsequent mr

exposure<- format_data(file_i,
  type = "exposure",
  snps = NULL,
  header = TRUE,
  phenotype_col = "olink_target_fullname",
  snp_col = "rsid",
  beta_col = "BETA",
  se_col = "SE",
  effect_allele_col = "A1",
  other_allele_col = "A2",
  pval_col = "P",
  samplesize_col = "N",
  id_col = "HGNC.symbol",
  chr_col = "CHROM",
  pos_col = "POS38",
  gene_col = "ensembl_id",
  eaf_col= "A1FREQ")

exposure$rsid<- exposure$SNP
exposure$pval<- exposure$pval.exposure

#Clumping

exposure_clumped<- ieugwasr::ld_clump(
  dat = exposure,
  clump_kb = 10000,
  clump_r2 = 0.01,
  clump_p = 0.99,
  pop = "EUR",
  bfile = "/path/REF_PANEL/EUR",
  plink_bin ="/hpcpath/plink-1.90/plink")

#Categorisation into cis and trans and estimation of f statistic

exposure_instruments<-  mrpipeline::calc_f_stat(exposure_clumped) %>%
  mrpipeline::cis_trans(values_col="id.exposure", chr_col="chr.exposure", 
  pos_col="pos.exposure", filter = "hgnc_symbol", build = "grch38") #UKB selected column is in hg38

exposure_instruments<-  exposure_instruments %>% 
  filter(!grepl('CHR', chromosome_name))

#Keeping variants with f>10

exposure_instruments<- exposure_instruments[which(exposure_instruments$f.stat.exposure>=10),]

#Addition here- removing duplicates generated by mr pipeline

exposure_instruments$toremove<- ifelse(exposure_instruments$gene.exposure!=exposure_instruments$ensembl_gene_id, "Remove", "Keep")
exposure_instruments<- exposure_instruments[which(exposure_instruments$toremove!="Remove"),]

#Looping over psychiatric outcomes

iterations= 1:8

for (var in iterations){

try ({
outcome <- TwoSampleMR::read_outcome_data(snps = exposure_instruments$SNP, filename = outcome_files[[var]], 
                        sep = "\t", snp_col = "SNP", beta_col = "logOR", 
                        se_col = "SE", effect_allele_col = "A1", 
                        other_allele_col = "A2", pval_col = "P", eaf_col="FRQ", chr_col= "CHR", pos_col="BP", id_col="pheno", 
						ncase_col="NCAS", ncontrol_col="NCON", samplesize_col="NTOT")
#Harmonisation

dat <- mrpipeline::harmonise(exposure_instruments, outcome, action = 2)

#Keeping those that pass harmonisation

dat<- dat[which(dat$mr_keep=="TRUE"),]

#The following steps until saving the harmonised file are necessary to save all infomation considered necessary for the supplement

dat<- merge(dat, file_df, by.x="SNP", by.y="rsid")

dat$marker<- paste0((dat$SNP), ":", (dat$chr.exposure), ":", (dat$id.exposure), ":", (dat$gene.exposure), ":", (dat$cistrans), ":", (dat$id.outcome), ":", (dat$UniProt), ":", (dat$olink_assay_ukb))

dat_final<- dat%>%dplyr::select("marker","id.exposure", "gene.exposure", "SNP", "chr.exposure", "pos.exposure",
								"other_allele.exposure", "effect_allele.exposure", "beta.exposure", "se.exposure", 
								"pval.exposure", "eaf.exposure", "samplesize.exposure", "id.exposure", "f.stat.exposure",
								"cistrans", "UniProt", "olink_assay_ukb", "chr.outcome", "pos.outcome",
								"other_allele.outcome", "effect_allele.outcome", "beta.outcome", "se.outcome", 
								"pval.outcome", "eaf.outcome", "samplesize.outcome", "ncase.outcome", "ncontrol.outcome",
								"id.outcome", "remove", "palindromic", "ambiguous", "mr_keep")

setwd("/path/UKB/MR/supplement")
if(file.exists("harmonised_ukb.txt") == TRUE) {
  write.table(dat_final,"harmonised_ukb.txt", sep="\t", quote=F, row.names=F, col.names=F, append=TRUE)
} else { 
  write.table(dat_final, "harmonised_ukb.txt", sep="\t", quote=F, row.names=F, append=FALSE)
}

#MR analysis

mr_res <- mrpipeline::do_mr(dat, f_cutoff = 10)

#Saving separately available IVW and individual Wald ratios

try ({mr_res_ivw<- mr_res[which(mr_res$method=="Inverse variance weighted"),]

mr_res_ivw_f<- mr_res_ivw %>% 
    mutate(snp = strsplit(as.character(snp), ",")) %>% 
    unnest(snp)
mr_res_ivw_f$snp<- gsub("\\s+", "", mr_res_ivw_f$snp)
	
mr_res_ivw_f<- as.data.frame(mr_res_ivw_f)

map<- dat%>%dplyr::select("marker", "SNP", "cistrans")

mr_res_ivw_ff<- merge(mr_res_ivw_f, map, by.x="snp", by.y="SNP")

mr_res_ivw_ff$marker<- paste0((mr_res_ivw_ff$marker), ":", "IVW")

mr_res_ivw_ff$notes<- ifelse(all(mr_res_ivw_ff$cistrans=="C"), "ALLCIS", 
						ifelse(all(mr_res_ivw_ff$cistrans=="T"), "ALLTRANS", "ATL1CIS"))
})


mr_res_wald<- mr_res[which(mr_res$method=="Wald ratio"),]

map<- dat%>%dplyr::select("marker", "SNP", "cistrans")
mr_res_wald_f<- merge(mr_res_wald, map, by.x="snp", by.y="SNP")
mr_res_wald_f$marker<- paste0((mr_res_wald_f$marker), ":", "WALD")

mr_res_wald_f$notes<- ifelse(nrow(mr_res_ivw)!=0, "PrioritiseIVW", "Thisisit")


setwd("/path/UKB/MR/results")
if(file.exists("ivw_results_ukb.txt") == TRUE) {
  write.table(mr_res_ivw_ff,"ivw_results_ukb.txt", sep="\t", quote=F, row.names=F, col.names=F, append=TRUE)
} else { 
  write.table(mr_res_ivw_ff, "ivw_results_ukb.txt", sep="\t", quote=F, row.names=F, append=FALSE)
}

if(file.exists("wald_results_ukb.txt") == TRUE) {
  write.table(mr_res_wald_f,"wald_results_ukb.txt", sep="\t", quote=F, row.names=F, col.names=F, append=TRUE)
} else { 
  write.table(mr_res_wald_f, "wald_results_ukb.txt", sep="\t", quote=F, row.names=F, append=FALSE)
}
})
}
}, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})


}})
