#Metabrain eQTL data region extraction for subsequent colocalisation analyses
#This script:
#Imports all Metabrain data
#Extracts genome-wide significant and independent immunological eQTLs
#Saves them for supplementary material
#Prioritises for reqion extraction cis eQTLs 
#Note that Metabrain had available cis eQTLs only

#Load metabrain cortex data 

library(readr)
all_metabrain<- read_table("/path/METABRAIN/2021-07-23-cortex-EUR-80PCs-chr_all.txt")
all_metabrain_df<- as.data.frame(all_metabrain)

#Import the markers included in inflammation panels I & II so that markers can be extracted

base<- read.table("/path/panel/UKB_panel_base.txt")
colnames(base)<- c("olinkid", "UniProtID", "HGNC", "Ensemblid")

#Merge the two files so that immunological markers from metabrain can be extracted

metabrain_im<- merge(all_metabrain_df, base, by.x="GeneSymbol", by.y="HGNC")

library(dplyr)
metabrain_im<- metabrain_im%>%select(Gene, GeneChr, GenePos, GeneSymbol, SNPChr, SNPPos, SNPEffectAlleleFreq, MetaP, MetaBeta, MetaSE, RSID, A1, A2)
metabrain_im$N<- 2970
metabrain_im$ensemblid<- gsub("\\..*", "", metabrain_im$Gene)

#Load necessary packages

library(mrpipeline)
library(dplyr)
library(biomaRt)
library(TwoSampleMR)
gwasvcf::set_bcftools("/hpcpath/bcftools")


mart.gene <- biomaRt::useMart(biomart = "ensembl",
                                  host="https://www.ensembl.org",
                                  dataset = "hsapiens_gene_ensembl")

#Identify data that pass the genome-wide significant threshold

files<- files[which(files$MetaP<=5e-08),]

files <- split(files, files$Gene)

#Starting the loop for region extraction

lapply(list(files), function(x){
  for(x in files) {
  
  tryCatch({

#Formating for clumping function

exposure<- format_data(
  x,
  type = "exposure",
  snps = NULL,
  header = TRUE,
  phenotype_col = "GeneSymbol",
  snp_col = "RSID",
  beta_col = "MetaBeta",
  se_col = "MetaSE",
  effect_allele_col = "A1",
  other_allele_col = "A2",
  pval_col = "MetaP",
  samplesize_col = "N",
  id_col = "GeneSymbol",
  chr_col = "SNPChr",
  pos_col = "SNPPos",
  gene_col = "ensemblid",
  eaf_col= "SNPEffectAlleleFreq"
)

exposure$rsid<- exposure$SNP
exposure$pval<- exposure$pval.exposure

#Clumping

exposure_clumped<- ieugwasr::ld_clump(
  dat = exposure,
  clump_kb = 10000,
  clump_r2 = 0.01,
  clump_p = 0.99,
  pop = "EUR",
  bfile = "/path/REF_PANEL/EUR",
  plink_bin ="/hpcpath/plink-1.90/plink")

#Estimating f statistic & cis/trans annotation (all cis in the case of metabrain)

exposure_instruments<-  mrpipeline::calc_f_stat(exposure_clumped) %>%
  mrpipeline::cis_trans(values_col="exposure", chr_col="chr.exposure", 
  pos_col="pos.exposure", filter = "hgnc_symbol", build = "grch38") 

exposure_instruments<-  exposure_instruments %>% 
  filter(!grepl('CHR', chromosome_name))

#Keeping variants that pass the F statistic

exposure_instruments<- exposure_instruments[which(exposure_instruments$f.stat.exposure>=10),]

#Removing duplicates generated by mr pipeline

exposure_instruments$remove<- ifelse(exposure_instruments$gene.exposure!=exposure_instruments$ensembl_gene_id, "Remove", "Keep")
exposure_instruments<- exposure_instruments[which(exposure_instruments$remove!="Remove"),]

#Keeping information necessary for supplement

exposure_instruments_final<- exposure_instruments%>%dplyr::select("exposure", "gene.exposure", "SNP", "chr.exposure", "pos.exposure",
								"other_allele.exposure", "effect_allele.exposure", "beta.exposure", "se.exposure", 
								"pval.exposure", "eaf.exposure", "samplesize.exposure", "f.stat.exposure",
								"cistrans")
								

setwd("/path/METABRAIN/MR/instruments")
if(file.exists("instruments_metabrain_update.txt") == TRUE) {
  write.table(exposure_instruments_final,"instruments_metabrain_update.txt", sep="\t", quote=F, row.names=F, col.names=F, append=TRUE)
} else { 
  write.table(exposure_instruments_final, "instruments_metabrain_update.txt", sep="\t", quote=F, row.names=F, append=FALSE)
}

#Until here we extract instruments

#From here onwards we extract regions

#Prioritising extraction and therefore subsequent colocalisation analyses for biomarkers with at least one cis pQTL
#Metabrain has only cis but for consistency across all scripts keeping the if/else conditions

if(any(exposure_instruments_final$cistrans=="C")){
instruments<- exposure_instruments_final[which(exposure_instruments_final$cistrans=="C"),]

map<- instruments %>% split(x=instruments, f=instruments$SNP)
  
  lapply(list(map), function(x){
  
  for(x in map) {

region<- x[c("SNP","chr.exposure","pos.exposure", "exposure", "cistrans", "gene.exposure")]

#Here we make an indicator with information that is useful for pwcoco loop to work

region$TopSNP<- paste0((x$SNP),
                     ":",
                     (x$chr.exposure), ":", (x$exposure),
                     ":", (x$gene.exposure), ":", (x$cistrans))


setwd("/path/METABRAIN/PWCOCO/regions")
if(file.exists("topregions_metabrain.txt") == TRUE) {
  write.table(region,"topregions_metabrain.txt", sep="\t", quote=F, row.names=F, col.names=F, append=TRUE)
} else { 
  write.table(region, "topregions_metabrain.txt", sep="\t", quote=F, row.names=F, append=FALSE)
}

#This indicator here is useful for naming the files- again for pwcoco loop to work and for retaining important information

snp_list<- paste0(region$SNP,":",region$chr.exposure, ":", region$exposure, ":", region$gene.exposure, ":", region$cistrans)
snp_list<- as.data.frame(snp_list)

#Extract regions for each gene of interest from the original metabrain file

files_gene<- metabrain_im[which(metabrain_im$ensemblid==region$gene.exposure),]

all_chr<- files_gene[which(files_gene$SNPChr==region$chr.exposure),]
all_pos<- all_chr[which(all_chr$SNPPos>=region$pos.exposure-500000 & all_chr$SNPPos<=region$pos.exposure+500000),]


variants_region <- all_pos %>% 
    dplyr::select("RSID", "A1", "A2", "SNPEffectAlleleFreq", "MetaBeta", "MetaSE", "MetaP", "N") 
    
variants_region_final<- variants_region %>% dplyr::rename(
      SNP = RSID,
      A1 = A1,
      A2 = A2,
      freq = SNPEffectAlleleFreq,
      b = MetaBeta,
      se = MetaSE,
      p = MetaP,
      N = N,
    ) 
	
variants_region_final<- as.data.frame(variants_region_final)

print(nrow(variants_region_final))

setwd("/path/METABRAIN/PWCOCO/regions/exposure")

snp<- snp_list$snp_list

file_out_snp<- paste0(snp, ".txt")
for(o in 1:length(snp)) {

write.table(variants_region_final, file_out_snp[o], sep="\t", quote=F, row.names=F, col.names=T)}

  
}
})}

#As noted above metabrain had cis only but for consistency with other scripts keeping the else condition (this condition exists in the case of trans variants)

else{
instruments<- exposure_instruments_final[which.min(exposure_instruments_final$pval.exposure),]

region<- instruments[c("SNP","chr.exposure","pos.exposure", "exposure", "cistrans", "gene.exposure")]

region$TopSNP<- paste0((instruments$SNP),
                     ":",
                     (instruments$chr.exposure), ":", (instruments$exposure),
                     ":", (instruments$gene.exposure), ":", (instruments$cistrans))

setwd("/path/METABRAIN/PWCOCO/regions")
if(file.exists("topregions_metabrain.txt") == TRUE) {
  write.table(region,"topregions_metabrain.txt", sep="\t", quote=F, row.names=F, col.names=F, append=TRUE)
} else { 
  write.table(region, "topregions_metabrain.txt", sep="\t", quote=F, row.names=F, append=FALSE)
}

snp_list<- paste0(region$SNP,":",region$chr.exposure, ":", region$exposure, ":", region$gene.exposure, ":", region$cistrans)
snp_list<- as.data.frame(snp_list)

files_gene<- metabrain_im[which(metabrain_im$ensemblid==region$gene.exposure),]

all_chr<- files_gene[which(files_gene$SNPChr==region$chr.exposure),]
all_pos<- all_chr[which(all_chr$SNPPos>=region$pos.exposure-500000 & all_chr$SNPPos<=region$pos.exposure+500000),]


variants_region <- all_pos %>% 
    dplyr::select("RSID", "A1", "A2", "SNPEffectAlleleFreq", "MetaBeta", "MetaSE", "MetaP", "N") 
    
variants_region_final<- variants_region %>% dplyr::rename(
      SNP = RSID,
      A1 = A1,
      A2 = A2,
      freq = SNPEffectAlleleFreq,
      b = MetaBeta,
      se = MetaSE,
      p = MetaP,
      N = N,
    ) 
	
variants_region_final<- as.data.frame(variants_region_final)

print(nrow(variants_region_final))

setwd("/path/METABRAIN/PWCOCO/regions/exposure")

snp<- snp_list$snp_list

file_out_snp<- paste0(snp, ".txt")

write.table(variants_region_final, file_out_snp, sep="\t", quote=F, row.names=F, col.names=T)}

}, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})

}})

